version: '3'

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
    volumes:
      - ./app:/app
    platform: linux/x86_64
    env_file:
      - .env
    ports:
      - "8100:8000"
    depends_on:
      - postgres_db
    networks:
      linklink_network:

  postgres_db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      linklink_network:

networks:
  linklink_network:
    driver: bridge
